### ISSUE TITLE
Null exception in deserialize

### ISSUE THREAD

**Issue by AshIceLoky** [rikimaru0345/Ceras#1]
Hi,

I create a List<Trade> (150,000 objects) ;
I try to serialize and deserialize but there is a NULL EXCEPTION

                var datas = Trade.Generate(150000);
                var serializer = new CerasSerializer();
                var serialize = serializer.Serialize(datas);
                var deserialize = serializer.Deserialize<List<Trade>>(serialize);

    public class Trade
    {
        public string Ticker;
        public bool IsValid;
        public DateTime DateAndTime;
        public float Price;
        public uint Size;
        public EExchange Exchange;
        public ETradeCondition Condition;
        public bool HasQuotes;
        public Nbbo Nbbo;

        public Trade() { }
    }

    public class Quote
    {
        public string Ticker;
        public DateTime DateAndTime;
        public float Bid;
        public uint BidSize;
        public EExchange BidExchange;
        public float Ask;
        public uint AskSize;
        public EExchange AskExchange;

        public Quote() { }
    }

The serialialization is OK, but in deserialize there is an exception NULL

		public void Deserialize(byte[] buffer, ref int offset, ref TCollection value)
		{
			// How many items?
			var itemCount = SerializerBinary.ReadUInt32(buffer, ref offset);

/////------------------------------------   EXCEPTION, VALUE IS NULL
			value.Clear();
/////------------------------------------   EXCEPTION

			for (int i = 0; i < itemCount; i++)
			{
				TItem item = default(TItem);
				_itemFormatter.Deserialize(buffer, ref offset, ref item);
				value.Add(item);
			}
		}

**Comment by rikimaru0345** [comment]
Try the latest commit.
I fixed a issue related to that a few hours ago. 
Let me know if it still happens then

**Comment by rikimaru0345** [comment]
Check the nested types. From your earlier post it looks like you also have an `EExchange` type.
Does that one have a parameterless constructor?

In the meantime I will improve the message so it says what type it is trying to instantiate.

**Comment by AshIceLoky** [comment]
EExchange and ETradeCondition are ENUM

**Comment by rikimaru0345** [comment]
I uploaded a commit for better error messages, it now includes the type name. Try it and let me know what type it cannot construct. :)

**Comment by AshIceLoky** [comment]
System.Exception : 'Cannot create an instance of type 'System.Linq.Enumerable+<TakeIterator>d__25`1[[TestSerialisation.Trade, TestSerialisation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]''

**Comment by AshIceLoky** [comment]
my bad.
After the first error on the deserializer I decreased the number of objects in the list to be sure it did not come from here.
I forgot to put the ToList ()

Now it's perfect.
