### ISSUE TITLE
Feature: "Serialization Constructors", factory methods, pooling, ...

### ISSUE THREAD

**Issue by rikimaru0345** [rikimaru0345/Ceras#22]
Serialization constructors are becoming more and more important. The latest feature requests need them indirectly as well.

### "What even is a 'serialization constructor'? Do we really need it? I've never heard of it, sounds useless!"

<details>
<summary>(Click here to expand; unless you already know...)

 
</summary>

#### Example 1
Pretty much nothing in the `System.Linq.Expressions.*` namespace has a public constructor.
So how do you use those types then?
There's the `Expression` class that has tons of static methods like `Expression.Block(...)` which instantiate all the expressions for you. So serializing/deserializing can't be done the normal way.
There are a few solutions:
- The "classic" solution: manually writing a formatter for every single type in that namespace. This will obviously work, but it will take ages to do...
- Saving the NodeType and content, then later using the static factory methods in Expression.* to re-creating the objects... (not so easy because objects depend on each other)
- Configure the types dynamically: include private fields for those objects, force "Overwrite ReadOnly Fields", and create objects from an uninitialized state. (This would be the easiest and most safe method to do when the API is done)

#### Example 2
```csharp
var myList = new List<int>() { 1, 2, 3, 4, 5 };
var roc = new ReadOnlyCollection(myList);
```
In case you've never seen or worked with a `ReadOnlyCollection`: It's just a collection that is initialized once at the start and can't be changed anymore after that (unless the underlying `IList<>` changes, then those changes are reflected in the `ReadOnlyCollection`). It's basically just a super simple wrapper around any given `IList<>`. Should you try to modify it in some way, it will just throw a `NotSupportedException`. Even if you'd try to be sneaky like `IList<int> castedToList = roc;` it wouldn't work...

So we see that it's not always possible to just `new()` an object and then fill its fields and properties.
Sometimes we're dealing with objects that have a certain way they're intended to be used / constructed.

### So what's a serialization constructor now!?!?
It's simply *"the constructor that the serializer is supposed to use when deserializing"*. It's not a fixed concept, it's rather a convention that some serializers have established.
Actually it doesn't even have to be a normal constructor on the object itself. As we've seen in the `Expression` example the "serialization constructor" might even be a static method somewhere (aka a "factory method").

</details>

*... so now that we know all that, we can now continue*

# Current workaround
In the current version (3.0.2) Ceras you can call `CerasSerializer.AddFormatterConstructedType(typeof(MyThing));` and implement a custom `IFormatter<MyThing>` and handle the construction yourself in there.

However, the goal of Ceras is to make a serializer that doesn't suck! And the current workaround does indeed suck. So that definitely has to be improved :smile: 

# Pooling
Object pooling is a closely related topic. Maybe your objects are expensive to create, or maybe you need to recycle objects to reduce GC pressure (hello Unity users :stuck_out_tongue_winking_eye:) ... 
In any case, "Pooling" essentially asking the same question: "How does Ceras obtain or create an object while deserializing?"

Ceras currently supports pooling through the two callbacks in the config: `Func<Type, object> ObjectFactoryMethod` and `Action<object> DiscardObjectMethod`.

A typical implementation of a `ObjectFactoryMethod` has to check what type is requested (maybe using multiple if()s, or a dictionary, ...) so it comes with a little overhead.
So pooling could be improved and implementing serialization-constructors is the perfect opportunity.

# API
So here's the preliminary API I came up with. I think it covers every conceivable situation.

```csharp

// Use 'new()', this is exactly what Ceras currently does.
config.ObjectConstruction.UseDefaultConstructor<Person>();


// Use 'FormatterServices.GetUninitializedObject()'. 
// Probably won't be used often (if at all), because of the much
// better / more performant options below
config.ObjectConstruction.UseUninitializedObject<Person>(); 


// User provided custom delegate to create an "empty" instance.
// Probably rarely used as well.
config.ObjectConstruction.UseDelegate<Person>( () => new Person() );


// Use the given MethodInfo by trying to matching field and property
// names to the arguments of the method. If the matching fails for any
// reason you can provide a "ParameterMapping" class as well that
// tells Ceras what field or property in the serialized data each parameter
// gets its value from. This is probably the most useful method of all of them.
config.ObjectConstruction.UseFactoryMethod<T>(constructorOrMethodInfoReturningT); 
        

// Convenience method. A wrapper around the previous method.
// The parameter is an 'Expression<Func<T>>', so you can very easily
// specify a method without having to use reflection to obtain a 'MethodInfo'
config.ObjectConstruction.UseFactoryMethod<Block>(() => BlockCreator.Create(...));


// Convenience Method: Takes a Type and forwards all its methods to 'UseFactoryMethod'
config.ObjectConstruction.UseFactory(typeof(MyStaticPool));


// Similar to UseFactory, but takes a instance of an object and tries to
// use each instance-method as a factory. This creates a closure, or in
// other words: it binds to the given instance.
config.ObjectConstruction.UseFactory(myFactoryInstance);

```

Some notes:

- Performance will stay a top-priority! If at all possible, Ceras will always "unpack" any delegates and compile target methods directly into its dynamically generated code, completely removing any  overhead.

- `UseFactory` is probably the most useful method because it allows you to very easily use your already existing pooling solution (however it might look like). Even if you don't have a class that directly matches the expected format, you can just create a class that forwards all method calls to your actual pool.

- This would replace the current approach, where you can only provide a callback like `Func<Type, object>` which always forces you to check the type. That costs some performance (only very little, but still) and leads to less readable code. This new API would solve these issues completely. 

- You won't have to call `AddFormatterConstructedType` anymore (in case you're using it). The new API would obviously not need that anymore.

**Comment by PolitovArtyom** [comment]
For my case i may need to configure falback from UseDefaultConstructor to UseUninitializedObject globally for all types. I can make it by implementing my own ObjectFactory. 
Could you provide public access to functionality of UseDefaultConstructor and UseUninitializedObject to reuse logic?

**Comment by rikimaru0345** [comment]
@PolitovArtyom 
> Could you provide public access to functionality of UseDefaultConstructor and UseUninitializedObject to reuse logic?

Could you elaborate what you mean by that?
The `ObjectFactoryMethod` as it exists right now would be completely removed and replaced by this new system. So there'd be no need to reuse anything anyway (unless I'm misunderstanding).

How/where would you want to reuse those two methods?

The actual logic behind those methods would just be setting a flag or enum in some internal structure in Ceras so different code gets generated.

If you want the actual implementation (which actually gets compiled), they're extremely simple:

UseDefaultConstructor: `return new MyObject();`
UseUninitializedObject: `return FormatterServices.GetUninitializedObject(typeof(MyObject));`

**Comment by PolitovArtyom** [comment]
If it's so simple, there is no need to reuse code. Thank you for feedback!

**Comment by rikimaru0345** [comment]
For anyone interested:

With commit https://github.com/rikimaru0345/Ceras/commit/5c10f30b40d90fc360a32922de99507675dce31f most preliminary work is complete for serialization constructors.

Virtually every imaginable way to construct objects is now supported.
Take a look at this code for some examples: https://github.com/rikimaru0345/Ceras/blob/master/samples/LiveTesting/Program.cs#L255-L369

There is still some minor work left to do regarding cleanup and improving the usability of some APIs but for the most part this feature is complete now and will soon be released.

**Comment by thorichelli** [comment]
I tried to replace our current serializer with Ceras but Serialization Constructors seems must for us. Some fields in our class such as Bitmap type fields cannot be serialized because it has no parameterless constructor. Keep up the good work!

**Comment by rikimaru0345** [comment]
@thorichelli The feature is pretty much done! :) If you are feeling adventurous you can the `master` branch; it has a lot of new stuff (but also some things that are still incomplete).

Could you tell me a bit more about your exact use-case though? We better make sure the feature (when it gets released) is actually what you are looking for. Now is the time where I could still get some changes in.

What kind of Bitmap class are you dealing with? The System.Drawing.Bitmap one?
Are you looking to transfer as little data as possible (a network situation), or are you looking for maximum speed (preferably blitting the data directly, even if it contains padding, alignment, ..., as long as it means more serialization/deserialization speed).

Feel free to join the discord if you want to as well, it's probably easier to talk about those kinds of things there.

**Comment by thorichelli** [comment]
I am gonna check the master branch :)
We are keeping test descriptions in binary files, there is a hierarchical structure in there and there may be cyclic references, a child element could keep its parent etc. Ceras is working way faster with lesser file size. My concern is faster serialization/deserialization, less memory usage and small file size and I am happy with the results so far. 

Some test description objects has System.Drawing.Bitmap typed fields and they need to be serialized too. Codebase is big and I don't prefer so much refactoring for now.  Thank you!

**Comment by DaniilSokolyuk** [comment]
Object pooling is nice! But what about array pool? Here for example https://github.com/rikimaru0345/Ceras/blob/0aa7affbe388162d12afc932ebe9ef4fce994e3d/src/Ceras/SerializerBinary.cs#L484
Maybe create IArrayPool<T> like this
https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/IArrayPool.cs
Put in settings, and use everywhere where arrays are allocated?

**Comment by rikimaru0345** [comment]
@DaniilSokolyuk 
It would certainly be possible. I have a question though.

At the moment those methods are static for performance reasons.
If you want `FastResize()` to respect a setting that is per-serializer, then it has to get a reference to it from  somewhere. That means the serializer or config either have to be passed down, or `SerializerBinary` has to become non-static (in that case, the `this` pointer is passed down implicitly, which - from a performance point of view - is the same thing).

One possible solution I could see would be to have static callbacks for Rent and Return.
The user would be able to just do something like `SerializerBinary.RentByteArray = MyRentMethod;`.

That way the feature would be essentially free from a performance perspective.

It would also have the additional advantage that multiple `CerasSerializer` instances would share a single pool (which is what you probably want anyway for the best possible cache coherency and maximum amount of shared memory shared whenever possible).

I'm not sure if there are any reasons to have it as an instance.

What do you think?

**Comment by DaniilSokolyuk** [comment]
@rikimaru0345 Sorry for the delayed response
Static callbacks for Rent and Return is good idea if you want to keep FastResize is static, or static property like SerializerBinery.ArrayPool = DefaultArrayPool.
Multiple `CerasSerializer` instances would share a single pool, its ok but customer does not always want to get data from the array pool.
MessagePack resolve this problem
https://github.com/neuecc/MessagePack-CSharp/blob/b9ec7fb4b12f9fc69c592b99ac0895ace0f11584/src/MessagePack/MessagePackSerializer.cs#L77
MessagePack pools is per thread like [ArrayPool.Shared](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Buffers/TlsOverPerCoreLockedStacksArrayPool.cs)

**Comment by rikimaru0345** [comment]
@DaniilSokolyuk 
Usually per-thread implementations are really slow, but this is a special case where I think it could be a really good idea; because the arrays are relatively rarely resized and have a long lifetime (or more like "actively used time") compared to the individual writes.
So it's not like we'd have to obtain a new buffer or do some costly operation on every single int that gets written or anything like that.

I like it :+1: 

But maybe we could make it even more efficient.

give me a moment, I will edit this post with another idea in a few minutes....

**Comment by rikimaru0345** [comment]
The request by @DaniilSokolyuk is now implemented in https://github.com/rikimaru0345/Ceras/commit/b51183d3783d11d62fe11a1b880f98e45e4172c3

I'm closing this since the original idea is already implemented as well, so everything is said and done :+1:

**Comment by rikimaru0345** [comment]
@thorichelli  check out commit https://github.com/rikimaru0345/Ceras/commit/b594d3c083b6f8dd647d1c07404e3c7e91d561d1
It has new settings in the config and a built-in formatter for bitmaps.
Let me know if that helps! :)

**Comment by thorichelli** [comment]
@rikimaru0345 waiting for new release to test :)
Thank you!

**Comment by rikimaru0345** [comment]
@thorichelli I'll publish a rc (release candidate) version of v4.0 on nuget today so people can test the new stuff :)

**Comment by pha3z** [comment]
I'm confused.  I came across this thread talking about the special object factory API.  It says the work is complete, but when I look through the repo I can't find it in the code!  What am I missing?
