### ISSUE TITLE
Trying to serialize Dictionary throws NullReferenceException

### ISSUE THREAD

**Issue by rcFMS** [rikimaru0345/Ceras#26]
Hey, 
I'm currently looking for a serializer to serialize and deserialize the data which gets generated by my Unity project. I previously had a look at neuecc's MessagePack but it has some limitations, mainly no support for circular references and the need to use attributes on all fields/properties. From some of the issues over there in which you seemed to have similar problems I found your Ceras serializer which looks promising.

I've tried out some simple things with it in a new empty project and found that circular references do indeed seem to work nicely (e.g. a "Node" class which has another Node as child).

One data type I need in my real project however is a ConcurrentDictionary<long, Node>. Trying to serialize/deserilize this kept throwing exceptions at me, even while simplifying the test project more and more. I finally arrived at the version below (SSCCE) which is just a simple Dictionary<int, string> but the exception persist...

	using System;
	using System.Collections;
	using System.Collections.Generic;
	using UnityEngine;
	using Ceras;

	[ExecuteInEditMode]
	[Serializable]
	public class Main : MonoBehaviour
	{
		#region Fields
		[SerializeField]
		private string name;
		[SerializeField]
		private int id;

		[NonSerialized]
		private Dictionary<int, string> simpleDict = new Dictionary<int, string>();
		[SerializeField]
		private byte[] serializedSimpleDict;

		[SerializeField]
		private bool doCreate;
		[SerializeField]
		private bool doSerialize;
		[SerializeField]
		private bool doPrint;
		[SerializeField]
		private bool doClear;
		[SerializeField]
		private bool doDeserialize;

		[NonSerialized]
		private CerasSerializer ceras;
		#endregion

		#region Properties
		
		#endregion

		#region Constructor
		
		#endregion

		#region Methods
		void Update()
		{
			if(doCreate)
			{
				simpleDict.Add(id, name);

				doCreate = false;
			}

			if(ceras == null)
			{
				SerializerConfig config = new SerializerConfig();
				config.DefaultTargets = TargetMember.AllFields;
				ceras = new CerasSerializer(config);

				Debug.Log("Created new CerasSerializer");
			}

			if(doSerialize)
			{
				int size = ceras.Serialize<Dictionary<int, string>>(simpleDict, ref serializedSimpleDict);
				Debug.Log("Serialized to " + size + " bytes");

				doSerialize = false;
			}

			if(doPrint)
			{
				Debug.Log(simpleDict.Count);
				foreach(KeyValuePair<int, string> kvp in simpleDict)
				{
					Debug.Log(kvp.Key + " = " + kvp.Value);
				}

				doPrint = false;
			}

			if(doClear)
			{
				simpleDict = new Dictionary<int, string>();

				doClear = false;
			}

			if(doDeserialize)
			{
				ceras.Deserialize<Dictionary<int, string>>(ref simpleDict, serializedSimpleDict);

				doDeserialize = false;
			}
		}
		#endregion
	}

This is the error I'm getting:

> NullReferenceException: Object reference not set to an instance of an object
Ceras.Formatters.ReferenceFormatter`1[T].Serialize (System.Byte[]& buffer, System.Int32& offset, T value) (at Assets/Plugins/Ceras/Formatters/ReferenceFormatter.cs:155)
(wrapper dynamic-method) System.Object.lambda_method(System.Runtime.CompilerServices.Closure,byte[]&,int&,System.Collections.Generic.Dictionary`2<int, string>)
Ceras.Formatters.DynamicObjectFormatter`1[T].Serialize (System.Byte[]& buffer, System.Int32& offset, T value) (at Assets/Plugins/Ceras/Formatters/DynamicObjectFormatter.cs:229)
(wrapper dynamic-method) System.Object.lambda_method(System.Runtime.CompilerServices.Closure,byte[]&,int&,System.Collections.Generic.Dictionary`2<int, string>)
Ceras.Formatters.ReferenceFormatter`1[T].Serialize (System.Byte[]& buffer, System.Int32& offset, T value) (at Assets/Plugins/Ceras/Formatters/ReferenceFormatter.cs:155)
Ceras.CerasSerializer.Serialize[T] (T obj, System.Byte[]& buffer, System.Int32 offset) (at Assets/Plugins/Ceras/CerasSerializer.cs:338)
Main.Update () (at Assets/Scripts/Main.cs:66)

Steps to reproduce:

1. Create the above script in a Unity project
2. Attach it as a Component to a GameObject in the Scene
3. Enter some values, e.g. "Alpha" and 123
4. Toggle the "Do Create" bool (quick and dirty way to add a button for testing)
5. Check with "Do Print" that the item got added (see in Console)
6. Press "Do Serialize" and the above exception is thrown (remember to manually untoggle "Do Serialize" again!)

Using this setup:

- Unity 2018.3.3f1
- Scripting Runtime Version = ".NET 4.x Equivalent"
- Scripting Backend = " IL2CPP"
- Api Compatibility Level = ".NET 4.x"
- Latest Ceras commit (Feb 10, 2019, 5c10f30b40d90fc360a32922de99507675dce31f)

Am I missing something? Or are Dictionaries not serializable?

**Comment by rikimaru0345** [comment]
Hey, dictionaries should definitely be serializable (as long as they implement the IDictionary or ICollection interface properly, meaning without throwing exceptions, like for example Readonly Collection (support for that one is practically done, just not released yet)) 

Does a normal dictionary work fine? 
The latest commit still has many work in progress changes, I will split out any wip stuff from the master branch with the next major release. 

I will be able to take a closer look at this in a couple of hours :)

**Comment by rikimaru0345** [comment]
I checked it out, seems like this is just a problem with the latest commit.
There are still some kinks to be worked out here.
I will probably have a fix commited and pushed sometime today. :ok_hand:

**Comment by rcFMS** [comment]
That'd be fantastic! I'd love to test it :)

Do you plan to create Releases here on github btw? Having a channel for stable builds would be nice.
Maybe it'd also be good to upload it to the Unity asset store to get more users and thus more feedback for faster/better development? ;)

**Comment by rikimaru0345** [comment]
That would be a good idea actually. I originally planned to post changelogs on rikidev.com but having them here in the dedicated releases section would be much better I think.

Uploading to the asset store, hmm, that's a bit of a hassle to keep it updated regularly with all the delays... but it would definitely be a good idea. I should probably make a forum post for that as well then. It's something I want to do, but I have to finish a few more important features first, so I'm not sure when that'll get done exactly.

As for testing, join the discord server if you want to; that way I can help out faster.
I'm still working on some related things (improved collection formatters) but the problem you reported is next on my todo list.

**Comment by rcFMS** [comment]
I appreciate it! Although I'm not a big fan of Discord myself, so I'd rather stick to github ;)
(I'll probably show up in Discord if something's on fire :P)

In the latest commit 1d7750eba921a6a3022029548b639ff5aaac9840 serializing/deserializing a ConcurrentDictionary<long, Node> is working again nicely though, I just had to remove a few "ref" keywords in the "Ceras.UnityAddon/Extension" class where "WriteFloat32FixedNoCheck" is called.

As a small side note regarding that Extension: It might be good to use the "#if UNITY_2017_2_OR_NEWER" / "#endif" preprocessor directives at the "#region 2017.2" / "#endregion" lines in order to prevent compiler errors with older Unity versions ;)

**Comment by rikimaru0345** [comment]
Hey, glad its working now! :smile: 

Be careful though with the newest version, there are still some more big changes coming pretty soon!
I've put the unity things on my todo list (#28)

The unity addon will most likely get **completely** reworked though.
Most of those types will be supported through https://github.com/rikimaru0345/Ceras/blob/1ae5b6b642b086b7526535e170256a4a8cf19c2a/src/Ceras/Formatters/ReinterpretFormatter.cs 

And the remaining ones (if any) will be explicitly handled through the new type-configuration API.

I'm almost sure that the whole addon will then only consist of a few configuration lines instead of many individual formatters :fireworks: :smile:

**Comment by rikimaru0345** [comment]
Since the master branch is still heavily wip, and one of the last commits has fixed it, I'll consider this issue as solved for now.

If its not, feel free to reopen it!

**Comment by rikimaru0345** [comment]
@rcFMS 
The unity related issues should all be fixed now in commit https://github.com/rikimaru0345/Ceras/commit/b60037d6867e9c37b3ebcba2aac235b760f4e790

**Comment by rcFMS** [comment]
I downloaded Unity 2017.1.5f1 using Unity Hub and opened a copy of my test project. When Unity tries to compile it throws some ~190 errors though, most because it's using an older C# version which doesnt support some of the syntactic sugar used in your code.

Also Ceras requires the "Allow 'unsafe' Code" option to be checked in the Player settings in the current Unity versions (using 2018.3.5 in my main project) but Unity 2017.1.5 doesnt even have that.

I guess it should be alright to drop support for Unity 2017 then?

**Comment by rikimaru0345** [comment]
If it were only just the syntax errors, I could (and would) definitely fix them.
But the unsafe option is a bit worrying. 
If there is really no way to enable that, then I guess there is no other way.
I would be surprised however if there wasn't some way to allow unsafe code in that version of Unity.

I'm currently looking into IL2CPP (on 2018.3 though) and how Ceras could support that, this is a good chance for me to also look into what you reported as well.

I'll try to get 2017.1.5f1 as well and see what I can do! :)

**Comment by rikimaru0345** [comment]
@rcFMS 

I fixed all the code that makes use of newer C# features for Unity 2017.1.

Here are the settings used to allow Ceras to be used:
![](https://i.imgur.com/2xGY5bO.png)

Otherwise this version of Unity requires a version that works with .NET 3.5, which would definitely be impossible to do because it does not contain some types Ceras depends on.

Seems to work fine now: **https://streamable.com/fvtc9**

I'll push the fixes in a moment.
I also removed a few of the manually written formatters from the unity extensions file because the reinterpret formatter can handle them just fine; and I added a few more types as well...

**Comment by rcFMS** [comment]
My thanks for your continued efforts as well! 😄 
With some more features added and some polishing I could see this becoming my go-to serializer! And I'm sure many other developers in the Unity community would also be highly interested, since Unity's default "JsonUtility" serializer has not aged well; it's slow and lacks vital features, such as e.g. circular references.

While the Ceras serializer sadly will not be able to fully replace JsonUtility (because JU is apparently deeply embedded in the entire Unity Editor UI so the Unity devs don't want to touch that code anymore since it would require *massive* amounts of rework across all core features and Packages from the Package Manager), Ceras can be dropped into the "Assets/Plugins" folder to be used as a third-party library to be easily used for all user-generated classes.


I tested the latest commit 064089c8fd13058733c7c760a4344067fc7267dc btw but I'm still getting 194 errors: 
![unbenannt](https://user-images.githubusercontent.com/40820493/53345766-ed4f3b80-3915-11e9-98d3-6a4ab68c6414.png)
I'm using the same Configuration settings in the Player Settings as you showed above.
I also created these files in the "Assets" folder, each containing only "-unsafe" (which, according to some forum posts I found, is supposedly the way to enable unsafe code in older Unity versions...):

- csc.rsp
- gmcs.rsp
- mcs.rsp
- smcs.rsp

Did you enable this some other way?

Tbh such an old Unity version isn't much of a priority to me personally. But it might be a nice-to-have for Ceras to support Unity versions as far back as possible so that even developers who are stuck with an older version might get to enjoy it 😉 

Sorry if this whole issue is going a bit offtopic btw, if you want you can move this to its own issue or something.

**Comment by rikimaru0345** [comment]
@rcFMS 
That means you're dropping the sources in.
In my tests I used the compiled version for net4.5, with that it should definitely work.
Can you try compiling the project in VS, and then moving in the output of the Debug or Release folder to Unity?

The compilation errors all certainly stem from the newly introduced syntax sugar of the newer C# versions.
I guess I should have clarified that I fixed the compilation errors in the Unity addon file, not globally in the wohle project.

So do this:
- Compile Ceras in VS (will produce output for all 3 target platforms)
- Take the content of the Debug/Release folder from the .NET 4.5 platform output and move it into your unity folder
- Take the individual .cs file from [here](https://github.com/rikimaru0345/Ceras/tree/master/src/Ceras.UnityAddon) and optionally use the AoT generator and the link.xml file if you're targetting IL2CPP, if not then the .cs file alone is enough.

Let me know if that way you still get any problems :+1:

**Comment by rikimaru0345** [comment]
Also, you don't need any sort of rsp file.
That is only needed when you want Unity to **compile** unsafe source-code.
If a already-compiled library like ceras.dll contains unsafe code it is annotated with the assembly attribute by the compiler (which some tools might look out for), but there will be no need to enable any sort of compatibility.

At least I was able to completely avoid any sort of .rsp or compiler config/response file stuff in my tests and I compiled for window standalone (normal mono runtime) and IL2CPP.

**Comment by rcFMS** [comment]
Ah, that makes sense.

I've got it working now as well, although it took me a while to update Visual Studio and install various packages until I got the right versions (.NET Core SDK 2.2, .NET Framework 4.7.2 SDK + Targeting Pack) since VS usually isn't my IDE of choice.
But thanks for the instructions!

Do you have any plans on how to handle releases btw? While dropping in the source files works fine in the newer Unity versions, for older Unity versions (or other platforms which cannot compile the source files themselves) it might be nice to have the precompiled versions available for download as well.

**Comment by rikimaru0345** [comment]
> I've got it working now as well, although it took me a while to update Visual Studio and install various packages until I got the right versions (.NET Core SDK 2.2, .NET Framework 4.7.2 SDK + Targeting Pack)

Oof! Haha! I can imagine that.
After researching what platforms I should support I had quite a bit of stuff to update and install as well :P 
I don't like having so many requirements to build Ceras, but it's either that, or creating "sub-optimal" builds. For example .net4.5 and 4.7 are explicitly support to minimize the number of assemblies that nuget drags in (in depth explanation in the comments here: https://github.com/rikimaru0345/Ceras/pull/8 ).

> since VS usually isn't my IDE of choice

That is surprising, I love VS, but to each their own :smile: 


> Do you have any plans on how to handle releases btw? While dropping in the source files works fine in the newer Unity versions, for older Unity versions (or other platforms which cannot compile the source files themselves) it might be nice to have the precompiled versions available for download as well.

There are 2 ways:

- The last badge on the main page links to the CI system: https://ci.appveyor.com/project/rikimaru0345/ceras/build/artifacts 
If you click on "artifacts" it will give you a list of all the outputs compiled for each individual platform.
![](https://i.imgur.com/tSUjA37.png)
I try to start appveyor builds pretty often in development, but I rarely push updates to nuget (because I don't have enough users/testers yet to know if a version would be stable enough for a nuget release).

- I want to use the "releases" section of GitHub as well as it'd be a great place to put changelogs. As soon as [the new/current v4.0-rc](https://www.nuget.org/packages/Ceras/4.0.0-rc) will be fully released (as a not-beta / not-rc version) I'll also post the full changelog there. 


For Unity users nuget will not be a good option (it **is** possible to get the dll out, but it's a super convoluted process that takes like 2 or 3 minutes... :sweat: ).

So for those people I'd suggest either taking the pre-compiled .zip from the CI directly (the appveyor link); or downloading it from the releases page (as soon as I put a release on there, which will be like in one or two days or so).

I will also add a pre-compiled version of the AoT-Formatter-Generator tool as a separate downloadable zip of course. (but I've yet to get some feedback on it from anyone :P)


Also, someone else (or was it you? I don't remember) asked about just putting Ceras on the Unity asset store.
I'd definitely love to do that! But getting anything up there is such a hassle.
Pushing fixes quickly is probably impossible because of the long delays until uploads get accepted/published. And I don't have an Icon/Image/Banner thing yet either. 
The upload tool is also pretty bad last I checked haha; I probably also need to make some sort of script to automate the upload process, maybe I could even let appveyor upload to unity directly? :bulb: 

Anyway, I'll definitely get around to doing that eventually! :smile:

**Comment by rcFMS** [comment]
> That is surprising, I love VS, but to each their own 😄

Since I mainly work with Unity my main IDE is (still) MonoDevelop. While it's not officially supported anymore (last version being 5.9.6 which comes with Unity 2017.4), newer Unity versions can still be configured to use it as IDE. The main reason I like it more than Visual Studio is that it's much more lightweight and has better syntax highlighting (especially with the Monokai theme I use). Of course the drawback is that it's not 100% as powerful as Visual Studio in a few aspects.

If you planned to provide precompiled versions for download anyway then that's good. I know some repositories where only the source code is provided and the users are expected to compile everything themselves (e.g. if you want to get a new version of [MonoDevelop for Windows](https://www.monodevelop.com/developers/building-monodevelop/#windows) they don't just provide an exe for some reason...) which can be a bit of a hassle.

> Also, someone else (or was it you? I don't remember)

Yes, that was me: https://github.com/rikimaru0345/Ceras/issues/26#issuecomment-463114684 ;)
I've seen the upload requirements Unity expects to be fulfilled and read that it can take some 4-6 weeks for a package to be approved. So the best approach might be to wait a bit after you release a stable version here on github and unless someone finds any problems with it then you could upload it to the Asset Store? And unless you fix something important in a minor version only upload major versions? Many uploaders also link to their github where users can get the latest version sooner if they need it.
Just a few thoughts ;)
