### ISSUE TITLE
Support for Optional Field Attribute

### ISSUE THREAD

**Issue by thorichelli** [rikimaru0345/Ceras#27]
Ignore and Include attributes are great features, but for some cases, optional field attribute is required. Are you planning to support it for future releases?

**Comment by rikimaru0345** [comment]
What does the optional field attribute do exactly?
How is it determined at serialization time whether a field gets included or not? Is there some sort of callback for each object? Or something like json has like `bool ShouldSerializeXXX()` ?

What would be some example scenarios here?
Reference-types can be null already, so I'm not sure what an optional field would do (unless you have a huge `struct` ?)

It's possible, I guess, but I definitely need some more context to fully understand what it does, why its important, how its used, ... :)

**Comment by thorichelli** [comment]
It is used for backward compatibility, we have old binary files that are created by old version of a class. When a new field is added to the class or a field is removed, deserialization fails if these fields are not tagged as optional.

**Comment by rikimaru0345** [comment]
Check out the version tolerance feature then. It does exactly what you want but better. (no attributes needed)

**Comment by thorichelli** [comment]
I added a field to a class, create an instance and serialize it to a  file, then i removed this field and try to deserialize it and it throwed an invalidcast exception. I think version tolerance cannot handle this situation.

**Comment by rikimaru0345** [comment]
It should handle that situation just fine.
Can you shown an example that has the problem?
You should use the latest version from nuget, not the latest commit in the repo (it is work in progress).

**Comment by rikimaru0345** [comment]
Also check out the example code here:
https://github.com/rikimaru0345/Ceras/blob/master/samples/LiveTesting/Program.cs#L1354
