### ISSUE TITLE
Cannot resolve types in referenced assemblies

### ISSUE THREAD

**Issue by thorichelli** [rikimaru0345/Ceras#30]
While deserialization, if the reference assembly is not resolved yet, Ceras throws a System.Exception.
Additional information: Cannot find type X after searching in all user provided assemblies and all loaded assemblies...

Maybe it is a normal behaviour of deserializer, but not sure. I came through with 3 different (not so cool) approach
1) I generated a dummy object with this type before deserialization and it worked.
2) I traversed the dependency hierarchy using a graph traversal logic and load all assemblies manually 
    with Assembly.Load
3) I tried to load all .dll files in the executable folder with Assembly.Load (in a try-catch scope)

Do I miss something?

**Comment by rikimaru0345** [comment]
There are multiple ways to solve this.
Tell me a bit more about the situation so I can help best.

What type is it that ceras is trying to deserialize that is not yet loaded?
Where does that type usually come from?

Are you able to directly access that type statically? Like a normal project/dll reference in visual studio?

Or is it like a sort of "plugin" that you have to discover through reflection?  Where you only know that the target types implement one of your "IPlugin" interface and you have to search for them...

**Comment by thorichelli** [comment]
Type is user-defined class, like "class MyClass"
This type is defined in assembly Ref1.dll and this assembly is referenced in the project references,
I could directly access this type statically, it is not a plugin. 

My guess is, this reference is not loaded by AppDomain till first usage for an optimization.
For instance, if a create a dummy object with type "MyClass", related assembly (Ref1.dll) is loaded now and then I could deserialize the binary successfully.

**Comment by rikimaru0345** [comment]
Yes, that makes sense.
That's a pretty simple scenario.

So what solution do you think would be the best actually?
- You could just access the type manually (writing `typeof(MyClass)` somewhere in the method) which is what you're already doing...
- I could modify the type-loader to expand the search to other assemblies, but I'm not sure if that will scale well. Gathering all assemblies and all types inside it.
- I could add some way where you could add custom assemblies to the type resolver. Maybe something like `config.SerachTypesInAssemblies.Add(typeof(MyClass).Assembly);`

Actually I'm not even sure if it is possible to find the assembly or if it gets loaded later and isn't even available until then...

I'll investigate that a bit later today.
Let me know what kind of solution you can imagine or what solution you would like to use, and then we can figure something out :)

**Comment by thorichelli** [comment]
I prefer Method3 ( _I could add some way where you could add custom assemblies to the type resolver_). But if you think it is not a neat way, I could survive with the first solution.

**Comment by rikimaru0345** [comment]
@thorichelli I'll add an api for that and post here once its done. :+1: 
When the other issues are fixed as well I'll upload a new rc version to nuget :)

**Comment by rikimaru0345** [comment]
This commit adds `CustomSearchAssemblies`
https://github.com/rikimaru0345/Ceras/commit/c3a2521f995a63085a855ee086909dbae5a71ed9

create a SimpleTypeBinder (or cast the one that is there by default in the config).
Then add your assemblies to `simpleTypeBinder.CustomSearchAssemblies`.
If you've created a new type binder you need to assign it to `config.Advanced.TypeBinder`.

That should solve it. Let me know if there are any problems :smile:

**Comment by rikimaru0345** [comment]
The new version is live on nuget now:
https://www.nuget.org/packages/Ceras/4.0.22
