### ISSUE TITLE
Bug: Bitmap deserialization problem

### ISSUE THREAD

**Issue by thorichelli** [rikimaru0345/Ceras#33]
When you serialize an object that has a bitmap type field and deserialize it back sequentially, it works great, but when you serialize it to a file and start a new application to deserialize it back, it throws System.ArgumentException, probably it uses some static information for deserialization, this is why it fails with a new application ( just a guess)

**To reproduce the bug:**

```
static void Test_Serialize()
{
	var element = new Element() { Id = 5, Name = "elem1" };
	element.pic = new Bitmap(@"C:\Users\eataseven\Documents\asd.png");

	SerializerConfig sc = new SerializerConfig();
	sc.DefaultTargets = TargetMember.AllFields;
	sc.Advanced.BitmapMode = BitmapMode.SaveAsBmp;
	sc.Advanced.RespectNonSerializedAttribute = false;
	sc.VersionTolerance.Mode = VersionToleranceMode.Standard;
	sc.VersionTolerance.VerifySizes = false;

	var ceras = new CerasSerializer(sc);
	var data = ceras.Serialize(element);
	File.WriteAllBytes("elem.bin", data);
}

static void Test_Deserialize()
{
	SerializerConfig sc = new SerializerConfig();
	sc.DefaultTargets = TargetMember.AllFields;
	sc.Advanced.BitmapMode = BitmapMode.SaveAsBmp;
	sc.Advanced.RespectNonSerializedAttribute = false;
	sc.VersionTolerance.Mode = VersionToleranceMode.Standard;
	sc.VersionTolerance.VerifySizes = false;

	var ceras = new CerasSerializer(sc);
	var element = ceras.Deserialize<Element>(File.ReadAllBytes("elem.bin"));
}

static void Main(string[] args)
{
	// works if run sequential
	Test_Serialize();
	Test_Deserialize();

	// does not work if 
	// comment out Test_Deserialize
	// run Test_Serialize only (elem.bin is generated)

	// comment out Test_Serialize, uncomment Test_Deserialize
	// run Test_Deserialize only 
        // throws exception
}
```

> An unhandled exception of type 'System.ArgumentException' occurred in System.Drawing.dll
> Additional information: Parameter is not valid.
>    at System.Drawing.Bitmap..ctor(Stream stream)
>    at Ceras.Formatters.BitmapFormatter.Deserialize(Byte[] buffer, Int32& offset, Bitmap& img)
>    at lambda_method(Closure , Byte[] , Int32& , Bitmap& )
>    at Ceras.Formatters.ReferenceFormatter`1.Deserialize(Byte[] buffer, Int32& offset, T& value)
>    at lambda_method(Closure , Byte[] , Int32& , Element& )
>    at Ceras.Helpers.SchemaDynamicFormatter`1.Deserialize(Byte[] buffer, Int32& offset, T& value)
>    at lambda_method(Closure , Byte[] , Int32& , Element& )
>    at Ceras.Formatters.ReferenceFormatter`1.Deserialize(Byte[] buffer, Int32& offset, T& value)
>    at Ceras.CerasSerializer.Deserialize[T](T& value, Byte[] buffer, Int32& offset, Int32 expectedReadLength)
>    at Ceras.CerasSerializer.Deserialize[T](Byte[] buffer)
>    at CerasSerializerTest.Program.Test_Deserialize() in C:\Users\eataseven\Documents\Visual Studio 2010\Projects\GMHTestSuite\CerasSerializerTest\Program.cs:line 668
>    at CerasSerializerTest.Program.Main(String[] args) in C:\Users\eataseven\Documents\Visual Studio 2010\Projects\GMHTestSuite\CerasSerializerTest\Program.cs:line 677
>    at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
>    at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
>    at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()

**Platform:**
Ceras 4.0.26 - net4.5 - Win7

**Comment by rikimaru0345** [comment]
Thanks for the report!
I was able to reproduce the problem and fix it (together with other improvements) in 4.0.27.
The update should be available on nuget in a few minutes.
