### ISSUE TITLE
Bug: VersionToleranceMode.Standard causes deserialization to fail

### ISSUE THREAD

**Issue by Drachenkaetzchen** [rikimaru0345/Ceras#35]
First of all, thank you for Ceras!

**Describe the bug**

When using `VersionToleranceMode.Standard`, the deserialization fails with 

```System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.```

This only happens when deserializing the second `Plugin`. A workaround would be to construct a new instance of the serializer after each deserialization. 

**How to reproduce the bug**

```csharp
namespace Repro
{
    public class PluginLocation
    {
        public string PluginName { get; set; }
    }

    public class Plugin
    {
        public PluginLocation PluginLocation { get; set; }
    }

    public class Program
    {
        [STAThread]
        static void Main(string[] args)
        {
            var plugin = new Plugin();
            var plugin2 = new Plugin();

            var serializerConfig = new SerializerConfig();
            serializerConfig.VersionTolerance.Mode = VersionToleranceMode.Standard;
            var s = new CerasSerializer(serializerConfig);

            var data = s.Serialize(plugin);
            var data2 = s.Serialize(plugin2);

            s.Deserialize<Plugin>(data);
            s.Deserialize<Plugin>(data2); // This will fail
        }
    }
}
```

**Platform**
- net4.7.2

**Comment by rikimaru0345** [comment]
Thanks for the report, I'll take a look at the problem as soon as possible!

**Comment by rikimaru0345** [comment]
I found and fixed the bug. 
The commit will be pushed as soon as I'm done writing the unit test for this.

**Comment by rikimaru0345** [comment]
v4.0.30 should appear on nuget in 10-30minutes.

https://ci.appveyor.com/project/rikimaru0345/ceras/deployment/1953591

@Drachenkaetzchen 
Thanks for the bug report and the repro code. That made tracking the bug down and fixing it pretty fast.

Let me know if there are any other problems or anything I can help with.

**Comment by Drachenkaetzchen** [comment]
You're welcome! I can confirm that the new release fixes the issue. And yes, I'll report more bugs if I find some ;)
