### ISSUE TITLE
Bug: VersionToleranceMode.Standard causes InvalidOperationException on deserialization

### ISSUE THREAD

**Issue by thorichelli** [rikimaru0345/Ceras#36]
If VersionTolerance is set on SerializerConfig, public and protected fields in base class causes System.InvalidOperationException.

```
public abstract class BaseCls
{
    public string Field1;
}
public class TestCls : BaseCls
{
}
void Driver()
{
    var sc = new SerializerConfig();
    sc.DefaultTargets = TargetMember.AllFields;
    sc.VersionTolerance.Mode = VersionToleranceMode.Standart;
    
    var ceras = new CerasSerializer(sc);
    TestCls tc = new TestCls();
    TestCls tcClone = ceras.Deserialize<TestCls>(ceras.Serialize(tc));
}
```

> System.InvalidOperationException
> Message: member not found
> 
> at Ceras.TypeConfig.GetMemberConfig(MemberInfo memberInfo)
> at Ceras.CerasSerializer.REadScheme(Byte[] buffer, Int32& offset, Type type, Boolean isStatic)
> ...
> 

Platform
Win7, net4.5, Version: 4.0.30.0

**Comment by rikimaru0345** [comment]
Thanks for reporting.
The repro code made this really easy to find and fix, thanks! :smile: 

An updated build will be pushed to nuget in a few minutes.
