### ISSUE TITLE
performance improvement

### ISSUE THREAD

**Issue by fredliex** [rikimaru0345/Ceras#38]
hi 
maybe you want follow that 
AArnott/MessagePack-CSharp#27

**Comment by rikimaru0345** [comment]
Ceras supports this in a different way already. 

https://github.com/rikimaru0345/Ceras/blob/master/src/Ceras/Config/BufferPooling/CerasBufferPool.cs

It's not that similar but it does solve the same problem with the same efficiency.

If you think there is something more we can do here, feel free to reopen the issue. :)
