### ISSUE TITLE
have demo for network?

### ISSUE THREAD

**Issue by yuzd** [rikimaru0345/Ceras#39]
now i use protobuf in post request and recive request  (serialize object to outputStream and deserialize from inputStream):

ProtoBuf.Serializer.NonGeneric.Serialize(toStream, object);

ProtoBuf.Serializer.NonGeneric.Deserialize(type, fromStream);

if change to ceras,does performance is good then protobuf?

**Comment by rikimaru0345** [comment]
In general Ceras is faster than protobuf.

As for an example, take a look here:
https://www.rikidev.com/networking-with-ceras-part-1/

For best **performance** there are many things that you can improve compared to that little demo. 
The demo I linked above is only intended to show how easy it is to use.

For maximum performance you should use KnownTypes, disable reference serialization if you don't need it, re-use your serialization buffers, ...

**Comment by yuzd** [comment]
thanks ! i will try it
