### ISSUE TITLE
Bug: AOT generator Deserialize functions don't compile when target class has serialized properties

### ISSUE THREAD

**Issue by zvinless** [rikimaru0345/Ceras#48]
Remember: The more faster I can reproduce your problem, the faster I can fix it :P

**Describe the bug**
- What are you trying to do?
Generate formatters for a class type with serialized properties, e.g.:
```csharp
[CerasAutoGenFormatter]
public class TestWithProperty
{
	int anInt;
	public int AnInt { get => anInt; set => anInt = value; }
}
```

The `Deserialize` function of the generated formatter ends up looking like:
```csharp
public void Deserialize(byte[] buffer, ref int offset, ref TestWithProperty value)
{
	_intFormatter.Deserialize(buffer, ref offset, ref value.AnInt);
}
```
which doesn't compile since properties can't be passed as `ref` parameters.

- What do you think **should** happen?
I'm not actually sure. If there's a way to support this easily without passing the property as a `ref` parameter, then that! Otherwise, omit the property and warn the user?

**How to reproduce the bug**
See above; use the provided class example with the AotGenerator tool (using the `[CerasAutoGenFormatter]` attribute to tag the class) and then try compile the generated output in a project.

**Platform**
- Which version of Ceras are you using? net4.5, net4.7+, or netstandard2.0?
netstandard2.0

- Are you using Unity? If so, what version? (2018.1, 2018.2, ...)
2018.3.14f1

- If you are using Unity, are you using IL2CPP?
I intend to!

**Comment by rikimaru0345** [comment]
Thanks for reporting. I'll push a fix for this soon.
