### ISSUE TITLE
Bug: AOT generated formatters are not used in AOT mode

### ISSUE THREAD

**Issue by zvinless** [rikimaru0345/Ceras#50]
Remember: The more faster I can reproduce your problem, the faster I can fix it :P

**Describe the bug**
- What are you trying to do?
Use generated formatters for classes in AOT mode, e.g.:
```csharp
[CerasAutoGenFormatter]
public class TestAot
{
	public int anInt;
}
```
- What do you think **should** happen? 
The generated formatter should get used automatically when trying to serialize the `TestAot` class, and I should be able to serialize an instance of it in AOT mode. I'd also be fine with needing to manually call `UseFormatters` on the generated class if that would make sense. 

- What is actually happening?
When I try to serialize a`TestAot` object, I get: `InvalidOperationException: No formatter for the Type 'TestAot' was found. Ceras is trying to fall back to the DynamicFormatter, but that formatter will never work in on AoT compiled platforms. Use the code generator tool to automatically generate a formatter for this type.`

As far as I can tell, the generated script's `UseFormatters(SerializerConfig config)` function is never called. If I change the generated class to be public and call it manually, I get a different error when trying to serialize: 
```
ArgumentNullException: Value cannot be null.
Parameter name: method
System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method, System.Boolean throwOnBindFailure, System.Boolean allowClosed) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
Ceras.Formatters.ReferenceFormatter`1[T].CreateSpecificSerializerDispatcher_Aot (System.Type type, Ceras.Formatters.IFormatter specificFormatter) (at <7a851d90e8b74dd689c0d63616010e91>:0)
Ceras.Formatters.ReferenceFormatter`1[T].GetOrCreateEntry (System.Type type) (at <7a851d90e8b74dd689c0d63616010e91>:0)
Ceras.Formatters.ReferenceFormatter`1[T].Serialize (System.Byte[]& buffer, System.Int32& offset, T value) (at <7a851d90e8b74dd689c0d63616010e91>:0)
Ceras.CerasSerializer.Serialize[T] (T obj, System.Byte[]& buffer, System.Int32 offset) (at <7a851d90e8b74dd689c0d63616010e91>:0)
Ceras.CerasSerializer.Serialize[T] (T obj) (at <7a851d90e8b74dd689c0d63616010e91>:0)
```

**How to reproduce the bug**
Use the above test class and generate an AOT formatter using the AotGenerator tool. Here is my test code:
```csharp
var config = new Ceras.SerializerConfig();
config.Advanced.AotMode = Ceras.AotMode.Enabled;

// This is what I mean by calling this function manually.
// You need to modify the generated code for it to be accessible.
// Ceras.GeneratedFormatters.GeneratedFormatters.UseFormatters(config);

var serializer = new Ceras.CerasSerializer(config);
var o = new TestAot { anInt = 1 };
var bytes = serializer.Serialize(o);
o = serializer.Deserialize<TestAot>(bytes);
```

**Platform**
- Which version of Ceras are you using? net4.5, net4.7+, or netstandard2.0?
netstandard2.0

- Are you using Unity? If so, what version? (2018.1, 2018.2, ...)
2018.3.14f1

- If you are using Unity, are you using IL2CPP?
No, I'm doing this in the editor

**Comment by rikimaru0345** [comment]
Hey, thanks for reporting this!

> As far as I can tell, the generated script's UseFormatters(SerializerConfig config) function is never called. 

You should in fact be calling that manually from your code ([see step 4 here](https://github.com/rikimaru0345/Ceras/wiki/Unity-IL2CPP-(iOS-and-AOT))).

There is a reason for that though.
How would your a created CerasSerializer instance ever know about those formatters? And how would it know if you even intend them to be used? Like even if there was a way to automatically let a CerasSerializer search for all IFormatters (ignoring the huge amount of time that'd take), it is possible that you (the user) have some formatters that you intend to use with one instance (lets say for networking ), and another set of formatters you for other things (for, lets say, creating a save-game file).
If there's something I missed, feel free to let me know of course :)

> If I change the generated class to be public and call it manually, I get a different error when trying to serialize:

I wonder about the need for the class to be public. The source code file is supposed to be right in there with your other project files, so only the method itself has to be public (and it is), but not the class (there should be no problem accessing an internal static class as long as it is in the same project, no?).

As for the other error you've reported. That is indeed a bug!
I'll take an in-depth look at what is going on there and report back when I find something.

**Comment by zvinless** [comment]
I think it makes complete sense to need to call that function manually! I much prefer that to, e.g., using virtual or partial functions.

As for the protection level--sorry, forgot to specify, I was doing this test from an editor script in Unity, which is in a different assembly from the game code; since the class is internal it's not visible to the editor assembly without modifications. This was my source of confusion since about needing to call `UseFormatters`.
