### ISSUE TITLE
Sign Ceras library

### ISSUE THREAD

**Issue by NilFusion** [rikimaru0345/Ceras#54]
The library cannot be currently referenced from a signed assembly:

`System.IO.FileLoadException: 'Could not load file or assembly 'Ceras, Version=4.0.40.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'`

**Comment by rikimaru0345** [comment]
I've read up on signing / strong naming a bit and it seems it's a really bad idea to do for open source projects. See here:

- https://jeremydmiller.com/2014/04/28/fubumvc-lessons-learned-strong-naming-woes-and-workarounds/
- https://github.com/sprache/Sprache/issues/87

It seems you should be able to very easily sign the library yourself using [**strongnamer**](https://github.com/dsplaisted/strongnamer), could you try that?

**Comment by NilFusion** [comment]
Thank you! Strongnamer solved the issue.
