### ISSUE TITLE
Bug: AotGenerator outputs broken code

### ISSUE THREAD

**Issue by huepat** [rikimaru0345/Ceras#59]
Hi,

I'm trying to use Ceras for a TCP client in a Unity app running on a Microsoft HoloLens (UWP).
I'm following [this](https://github.com/rikimaru0345/Ceras/wiki/Unity-IL2CPP-(iOS-and-AOT)) guide and I have problems at step 3) when generating formatters with AotGenerator.exe.
I reduced my problems to a simple case:

**Describe the bug**
- What are you trying to do?
Generating formatters for this class with AotGenerator.exe:
```
using Ceras.Formatters.AotGenerator;
using System.Collections.Generic;

[CerasAutoGenFormatter]
public class TestClass {
    public int l1;
    public int l2;
    public List<int> l;

    public TestClass() { }

    public TestClass(int l1, int l2, List<int> l) {
        this.l1 = l1;
        this.l2 = l2;
        this.l = l;
    }
}
```

- What do you think **should** happen? 
resulting cs file should be syntacticly correct and working.

- What is actually happening?
```
using Ceras;
using Ceras.Formatters;
namespace Ceras.GeneratedFormatters
{

    static class GeneratedFormatters
    {
        internal static void UseFormatters(SerializerConfig config)
        {
            config.ConfigType<TestClass>().CustomFormatter = new TestClassFormatter();
        }
    }

    internal class TestClassFormatter : IFormatter<TestClass>
    {
        IFormatter<System.Collections.Generic.List`1[[System.Int32, mscorlib, Version = 4.0.0.0, Culture = neutral, PublicKeyToken = b77a5c561934e089]]> _list`1Formatter;
 IFormatter<System.Int32> _int32Formatter;
        IFormatter<System.Int32> _int32Formatter;

        public void Serialize(ref byte[] buffer, ref int offset, TestClass value)
        {
            _list`1Formatter.Serialize(ref buffer, ref offset, value.l);
            _int32Formatter.Serialize(ref buffer, ref offset, value.l1);
            _int32Formatter.Serialize(ref buffer, ref offset, value.l2);
        }

        public void Deserialize(byte[] buffer, ref int offset, ref TestClass value)
        {
            _list`1Formatter.Deserialize(buffer, ref offset, ref value.l);
            _int32Formatter.Deserialize(buffer, ref offset, ref value.l1);
            _int32Formatter.Deserialize(buffer, ref offset, ref value.l2);
        }
    }

}
```
Errors relating to naming ambiguity caused by "_int32Formatter" and broken syntax from 
"_list`1Formatter".

**How to reproduce the bug**
- Create new Unity 3D project
- Add Ceras according to [here](https://github.com/rikimaru0345/Ceras/wiki/Usage-with-Unity)
- Create TestClass.cs in Assets folder (code see above)
- build project (for build settings see screenshot)
![grafik](https://user-images.githubusercontent.com/13088760/61799871-33a8b800-ae2c-11e9-8419-2817f148fe9a.png)
- run `Ceras.AotGenerator.exe <UNITY_BUILD_DIRECTORY>\Test\Managed\Assembly-CSharp.dll AotGeneratedFormatters_Test.cs`

**Platform**
- Which version of Ceras are you using? net4.5, net4.7+, or netstandard2.0?
Ceras4.7 and AotGenerator from [here](https://ci.appveyor.com/project/rikimaru0345/ceras/build/artifacts)

- Are you using Unity? If so, what version? (2018.1, 2018.2, ...)
2019.1.9f1

- If you are using Unity, are you using IL2CPP?
yes

I can fix the file manually for now, but it would be cool to get this working.

Best regards

**Comment by rikimaru0345** [comment]
Thanks for reporting!
Should be an easy fix, I'll take care of it in a few hours :)

**Comment by rikimaru0345** [comment]
Just a quick update: 
This issue is pretty much fixed by the major refactorings in how the aot generator works in v5.
In v5 the code is now generated from the actual expression tree, instead of generating any strings myself.

There are, however, some more things blocking v5 that I'm working on right now. 

You can track the progress here: #53 and by observing the commit log of the v5 branch:
https://github.com/rikimaru0345/Ceras/tree/Ceras-v5

**Comment by rikimaru0345** [comment]
The AotGenerator has gotten an update in the current version! The guide was also updated: https://github.com/rikimaru0345/Ceras/wiki/Usage-with-Unity
Biggest change: to use Ceras in Unity you should use the source code

With that this issue should be fixed. :)
