### ISSUE TITLE
Bug: [Regression] Incorrect handling of hash code collisions

### ISSUE THREAD

**Issue by janruo** [rikimaru0345/Ceras#67]
I'm serializing and deserializing things that contain `Coordinate` objects from [NetTopologySuite](https://github.com/NetTopologySuite/NetTopologySuite) (v2.0.0):
- The [`Coordinate`](https://github.com/NetTopologySuite/NetTopologySuite/blob/v2.0.0/NetTopologySuite/Geometries/Coordinate.cs) class is a pair of numbers (X, Y).
- [`CoordinateZ`](https://github.com/NetTopologySuite/NetTopologySuite/blob/v2.0.0/NetTopologySuite/Geometries/CoordinateZ.cs) extends `Coordinate` by adding a third value (X, Y, Z).
- [`CoordinateZM`](https://github.com/NetTopologySuite/NetTopologySuite/blob/v2.0.0/NetTopologySuite/Geometries/CoordinateZM.cs) extends `CoordinateZ` by adding a fourth value (X, Y, Z, M).

However, `CoordinateZ` and `CoordinateZM` use the `GetHashCode` implementation from `Coordinate`, so the Z and M values are ignored when the hash is calculated, so collisions can easily occur.

I haven't done extensive testing or research, but based on the example code below it looks like when Ceras encounters a new object with a hash code it has seen before, it just uses the previously cached reference, even though they are actually different objects. Or something like that.

This happens in versions >=4.0.36. Version 4.0.35 works fine, so I think it was caused by commit 5ae21c1d, since that seems to be the only commit between those two versions.

**Repro steps**
1. Create an empty project (I used .NET Core 2.1)
2. Install NetTopologySuite 2.0.0
3. Install Ceras (any version >=4.0.36)
4. Run the repro code below

**Expected results**
The code should print the following (4.0.35):
```
Original list hash codes:
2108709609
2108709609
2108709609
2108709609

Original list values:
(1, 2)
(1, 2, 3)
(1, 2, 10000)
(1, 2, 5, m=100)

New list values:
(1, 2)
(1, 2, 3)
(1, 2, 10000)
(1, 2, 5, m=100)
```

**Actual results**
The code prints the following (4.0.36+):
```
Original list hash codes:
2108709609
2108709609
2108709609
2108709609

Original list values:
(1, 2)
(1, 2, 3)
(1, 2, 10000)
(1, 2, 5, m=100)

New list values:
(1, 2)
(1, 2)
(1, 2)
(1, 2)
```

**Repro code**
```cs
using Ceras;
using Ceras.Formatters;
using NetTopologySuite.Geometries;
using System;
using System.Collections.Generic;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // Coordinate and CoordinateZ contain properties that throw when setting the value.
            // Use custom formatters to only set values to supported properties.
            var config = new SerializerConfig();
            config.OnResolveFormatter.Add((s, t) =>
            {
                if (t == typeof(Coordinate))
                    return new CoordinateFormatter();

                if (t == typeof(CoordinateZ))
                    return new CoordinateZFormatter();

                return null;
            });
            var serializer = new CerasSerializer(config);

            var list = new List<Coordinate>
            {
                new Coordinate(1, 2),
                new CoordinateZ(1, 2, 3),
                new CoordinateZ(1, 2, 10000),
                new CoordinateZM(1, 2, 5, 100)
            };

            var bytes = serializer.Serialize(list);
            var newList = serializer.Deserialize<List<Coordinate>>(bytes);

            Console.WriteLine("Original list hash codes:");
            list.ForEach(x => Console.WriteLine(x.GetHashCode()));
            
            Console.WriteLine("\nOriginal list values:");
            list.ForEach(Console.WriteLine);

            Console.WriteLine("\nNew list values:");
            newList.ForEach(Console.WriteLine);
        }
    }

    class CoordinateFormatter : IFormatter<Coordinate>
    {
        public void Serialize(ref byte[] buffer, ref int offset, Coordinate value)
        {
            SerializerBinary.WriteDouble64Fixed(ref buffer, ref offset, value.X);
            SerializerBinary.WriteDouble64Fixed(ref buffer, ref offset, value.Y);
        }

        public void Deserialize(byte[] buffer, ref int offset, ref Coordinate value)
        {
            value.X = SerializerBinary.ReadDouble64Fixed(buffer, ref offset);
            value.Y = SerializerBinary.ReadDouble64Fixed(buffer, ref offset);
        }
    }

    class CoordinateZFormatter : IFormatter<CoordinateZ>
    {
        public void Serialize(ref byte[] buffer, ref int offset, CoordinateZ value)
        {
            SerializerBinary.WriteDouble64Fixed(ref buffer, ref offset, value.X);
            SerializerBinary.WriteDouble64Fixed(ref buffer, ref offset, value.Y);
            SerializerBinary.WriteDouble64Fixed(ref buffer, ref offset, value.Z);
        }

        public void Deserialize(byte[] buffer, ref int offset, ref CoordinateZ value)
        {
            value.X = SerializerBinary.ReadDouble64Fixed(buffer, ref offset);
            value.Y = SerializerBinary.ReadDouble64Fixed(buffer, ref offset);
            value.Z = SerializerBinary.ReadDouble64Fixed(buffer, ref offset);
        }
    }
}
```

**Comment by rikimaru0345** [comment]
This is a pretty serious problem.
Thanks for taking the time to write such a good report.

I'm currently very busy, but I want to get this fixed asap. 
I will look into it over the next days.

**Comment by janruo** [comment]
After a bit more digging, it seems that NetTopologySuite may be the cause of the problem here, not Ceras.

If I'm understanding the code correctly, v4.0.35 had a custom `RefDictionary` as an object cache that used `ReferenceEquals()`, so everything worked as expected. v4.0.36+ uses the standard `Dictionary`, which only checks `Equals()`.

And it turns out that NTS only implements `Equals()` for `Coordinate` and not for `CoordinateZ` and `CoordinateZM`, so weird stuff like this happens:

```cs
var c1 = new Coordinate(1, 2);
var c2 = new CoordinateZ(1, 2, 3);
var c3 = new CoordinateZM(1, 2, 3, 4);

Console.WriteLine(c1.Equals(c2)); // True
Console.WriteLine(c2.Equals(c3)); // True

var dict = new Dictionary<Coordinate, string>
{
    [c1] = "first",
    [c2] = "second",
    [c3] = "third"
};

Console.WriteLine(dict[c1]); // third
Console.WriteLine(dict.Count); // 1
```

Feel free to close the issue if you think it's working as intended. I'll open a new issue in NTS's repo for this.
