### ISSUE TITLE
Bug:Define MyCustomFormatter to serialize byte[] problem.

### ISSUE THREAD

**Issue by BeanTang** [rikimaru0345/Ceras#69]
Serialize the type (byte[])  from a CustomFormatter .The result is not what i wanted.
The code like this:

```
Internal class MyCustomFormatter:IFormatter<T>
{
        IFormatter<byte[]> bytesFormat;

         public void Serialize(ref byte[] buffer, ref int offse,T obj)
        {
                bytesFormat.Serialize(ref buffer, ref offset, obj.bytesFormat);
         }
}


var config = new SerializeConfig();
config.ConfigType<int>().CustomFormatter = new  MyCustomFormatter();
var ceras = new CerasSerializer(config);
var testObj  = new TestObj()
{
     Data =  System.Text.Encoding.UTF8.GetBytes(DateTimeOffset.Now.ToString());
 };
```

The results :
new CerasSerializer().Serialize(testObj)  
  Such as = 32 30 31 39 2f 31 30 2f 31 34 20 31 38 3a 35 38 3a 34 36 20 2b 30 38 3a 30 30 

ceras.Serialize(testobj)   = 32 30 31 39 2f 31 30 2f 31 34 20 31 38 3a 35 38 3a 34 36 20 2b 30 38 3a 30 30  00 00 00 00 00 00 00 00 00 00 00  ……  

This wasn't what a wanted to be. 

How about to wirte the  MyCustomFormatter?(I must write like that because i need to config with AotMod )  
 
Or how to Serialize  " byte[]"  in  IFormatter<byte[]> ?

**Comment by rikimaru0345** [comment]
If this is about the zero bytes at the end, then take a look at this method instead:

https://github.com/rikimaru0345/Ceras/blob/master/src/Ceras/CerasSerializer.cs#L384

It's much more efficient to serialize into a large buffer and then return the length.
The method I linked returns an array that has been cut to the right size though.

Feel free to reopen if needed :)
